name: Reusable Workflow
on:
  workflow_call:
    inputs:
      name:
        description: "Input description"
        type: string
        default: "Andy"
        required: false
    secrets:
      access-token:
        description: "Secret description"
        required: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -al
      - run: ls -al .github/
      - run: tree .github/
  log-context-and-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Dispay Github Context
        run: echo '${{ toJSON(github) }}'
      - name: Display name input
        run: echo ${{ inputs.name }}
      - name: Display access-token secret
        run: echo ${{ secrets.access-token }}